import { Inter } from "next/font/google";
import NavBar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";
import { getDataPrueba } from "@/helpers/getInfoTest";
import "./globals.css";
import InputBusqueda2 from "@/components/header/InputBusqueda2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="es">
      <body
        className={`${inter.className} flex flex-col min-h-[100vh] m-0`}
        suppressHydrationWarning={true}
      >
        <header>
          <NavBar  />
          <InputBusqueda2  />
        </header>
        {children}
        <Footer  />
      </body>
    </html>
  );
}
