import { Inter } from "next/font/google";
import NavBar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";
import { getDataPrueba } from "@/helpers/getInfoTest";
import "./globals.css";
import InputBusqueda from "@/components/header/InputBusqueda";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const info = await getDataPrueba(
    `https://testapi.tuentrada.com/api/v1/site/ayuda.tuentrada.com`
  );
  const { data } = info.data.products;

  return (
    <html lang="es">
      <body
        className={`${inter.className} flex flex-col min-h-[100vh] m-0`}
        suppressHydrationWarning={true}
      >
        <header>
          <NavBar data={data} />
          <InputBusqueda data={data} />
        </header>
        {children}
        <Footer data={data} />
      </body>
    </html>
  );
}
